# 1st stage: Build the application
FROM node:18 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# 2nd stage: Create the production image
FROM node:18 AS production
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm install --only=production

EXPOSE 3009
ENV NODE_ENV=production

# Command to run the app in production mode
CMD ["npm", "run", "start:prod"]
