version: '3.8'

services:
  application: 
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - application-network
    ports:
      - "3009:3009"  # Expose port 3000 (adjust if using a different port)
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=test@123
      - DATABASE_NAME=user_management
      - DATABASE_DEBUG=false
      - JWT_SECRET=mysecretkey
      - JWT_EXPIRES_IN=1d
      - UPLOAD_DIR=uploads
      - DATA_DIR=data
      - INGESTION_API=https://jsonplaceholder.typicode.com/
      - RUN_INGESTION_CRON=false
    depends_on:
      - db  # Ensure the database service is up before starting the app

  db:
    image: postgres:latest
    container_name: postgres-new
    environment:
      POSTGRES_PASSWORD: test@123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql to be executed on startup
    networks:
      - application-network

networks:
  application-network:
    driver: bridge
