name: Lint, Build, and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  lint-build-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        # Step 2: Set up Node.js (for running ESLint)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your project's version
        # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
        # Step 4: Run ESLint
      - name: Run ESLint
        run: npx lint-staged
        # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Step 6: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Step 7: Build and Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.stage.build
          push: true
          tags: dockermantu/multi-client:iam-service
